### ISSUE TITLE
Roam42 Error: can't find uid

### ISSUE THREAD

**Issue by AngelPone** [yoyooyooo/roam-enhance#4]
Error message "can't find uid" poped out when click `Click for references` button of a block, which disappeared when `roam-enhance` extension was disabled.

Error message in console:

```javascript
"TypeError: Cannot read property 'customCommands' of undefined
    at https://roam-enhance.vercel.app/main.js:1:32078
    at e (https://roam-enhance.vercel.app/main.js:1:31764)
    at https://roam-enhance.vercel.app/main.js:1:32001
    at https://roam-enhance.vercel.app/main.js:1:32005
    at https://roam-enhance.vercel.app/main.js:1:40351"

TypeError: Cannot read property 'id' of null
    at HTMLDocument.<anonymous> (template-button.js:1)
```

Roam42 version: `latest`

**Comment by yoyooyooo** [comment]
`template-button` 这个插件先注释掉吧。。我个人用的
